### PR TITLE
add 20.0.2 and 20.0.3

### PR DESCRIPTION
**Pull request by mbogner**

### CODE REVIEW

**Comment by mbogner** [comment]
Screenshot 2023-01-25 at 15 44 27

**Comment by ccouzens** [comment]
Thank you. I expect to have time to review and merge this weekend.

**Comment by mbogner** [comment]
> Thank you. I expect to have time to review and merge this weekend.

No worries. I was looking for an up2date version of the spec and simply built it based on the steps you provided. But checking the resulting swagger spec resulted in some errors as shown above. Sure that's coming from the source but it stops for example openapi-generator from working properly. do you already have seen this and have a solution? My solution was to comment out the referenced lines and postpone the problem until I need the calls ;-)

**Comment by ccouzens** [comment]
Merged. Thank you

> No worries. I was looking for an up2date version of the spec and simply built it based on the steps you provided. But checking the resulting swagger spec resulted in some errors as shown above. Sure that's coming from the source but it stops for example openapi-generator from working properly. do you already have seen this and have a solution? My solution was to comment out the referenced lines and postpone the problem until I need the calls ;-)

I've made this change c31b735f0a0679479a2e009dddb99bc8f2e91dfc. openapi-generator seems to work now on 20.0.2.

I've ignored the warnings about DELETE operations having a request body. They don't seem to cause any problems with openapi-generator. Also, it's that way in the [upstream documentation]( https://www.keycloak.org/docs-api/20.0.2/rest-api/index.html#_deleteclientscopemapping)

**Pull request merged**
